# TCL File Generated by Component Editor 13.0sp1
# Wed Mar 14 14:25:03 GMT 2018
# DO NOT MODIFY


# 
# FPTask8 "FPTask8" v0.1
#  2018.03.14.14:25:03
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module FPTask8
# 
set_module_property DESCRIPTION ""
set_module_property NAME FPTask8
set_module_property VERSION 0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME FPTask8
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL task8
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file task8.v VERILOG PATH ip/task8.v TOP_LEVEL_FILE
add_fileset_file altfp_add_sub0.v VERILOG PATH ip/altfp_add_sub0.v
add_fileset_file altfp_add_sub1.v VERILOG PATH ip/altfp_add_sub1.v
add_fileset_file altfp_mult0.v VERILOG PATH ip/altfp_mult0.v
add_fileset_file cordic_dsd_multicycle.v VERILOG PATH ip/cordic_dsd_multicycle.v
add_fileset_file cordicWrap.v VERILOG PATH ip/cordicWrap.v
add_fileset_file div2.v VERILOG PATH ip/div2.v
add_fileset_file divByn.v VERILOG PATH ip/divByn.v
add_fileset_file fixedtofloat.v VERILOG PATH ip/fixedtofloat.v
add_fileset_file floor.v VERILOG PATH ip/floor.v
add_fileset_file task8Timer.v VERILOG PATH ip/task8Timer.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 33
set_interface_property nios_custom_instruction_slave operands 1
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave dataout result Output 32

